export const TOGGLE_REDSHIFT = 'TOGGLE_REDSHIFT';
export const NIGHTTIME_SLIDER = 'NIGHTTIME_SLIDER';
export const DAYTIME_SLIDER = 'DAYTIME_SLIDER';
export const DEFAULT_LOCATION = 'DEFAULT_LOCATION';
export const SUNRISE_SUNSET = 'SUNRISE_SUNSET';
export const AUTOSTART = 'AUTOSTART';
